// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcFilmDunyasi.Data;

#nullable disable

namespace MvcFilmDunyasi.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230206063514_Ilk")]
    partial class Ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MvcFilmDunyasi.Data.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("Puan")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Filmler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Fight Club",
                            Puan = 8.7m,
                            Yil = 1999
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Inception",
                            Puan = 8.7m,
                            Yil = 2010
                        },
                        new
                        {
                            Id = 3,
                            Ad = "The Maxtrix",
                            Puan = 8.7m,
                            Yil = 1999
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Joker",
                            Puan = 8.3m,
                            Yil = 2019
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Die Hard",
                            Puan = 8.2m,
                            Yil = 1988
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Green Book",
                            Puan = 8.2m,
                            Yil = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
